// resources/assets/react/components/btn.js
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import PropTypes from 'prop-types'

class Btn extends Component {
  render () {
    let {route, link, text, className} = this.props
    return (
      route ? (
          <Link to={link} className={`btn ${className}`} data-text={text}>{text}<span className="text">{text}</span></Link>
        ) : (
          <a href={link} className={`btn ${className}`} target="_blank" rel="nofollow" data-text={text}>{text}<span className="text">{text}</span></a>
        )
    )
  }
}

Btn.defaultProps = {
  className: '',
  route: false
}

Btn.propTypes = {
  className: PropTypes.string,
  route: PropTypes.bool,
  link: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired
}

export default Btn

// resources/views/components/btn.vue
<template>
  <router-link v-if="route" :to="link" class="btn" :data-text="text">
    {{text}}
    <span class="text">{{text}}</span>
  </router-link>
  <a v-else :href="link" class="btn" :data-text="text" target="_blank">
    {{text}}
    <span class="text">{{text}}</span>
  </a>
</template>

<script>
  export default {
    props: ['text', 'link', 'route'],
    name: 'btn'
  }
</script>
