// resources/assets/react/containers/portfolio/all.jsx
import React, { useState, useRef } from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { clickYearTab } from '../../store/actions'
import Btn from '../../components/btn.jsx'

function Portfolios (props){
  const [toggle, setToggle] = useState(true)
  const list = useRef(null)
  const { portfolios, currentYear, tab, animation, routes } = props

  function changeYear (year) {
    if (toggle) {
      setToggle(false)

      const listBlock = list.current
      listBlock.classList.add('v-leave-active')

      setTimeout(async () => {
        await props.dispatch(clickYearTab(year))

        setTimeout(() => {
          listBlock.classList.add('v-enter-to')

          setTimeout(() => {
            listBlock.classList.remove('v-leave-active')
            listBlock.classList.remove('v-enter-to')

            setToggle(true)
          }, 400)
        }, 250)
      }, 300)
    }
  }

  return (
    <div className="portfolio box-sm">
      <nav className="portfolio__time">
        {Object.keys(portfolios.years).length > 0 &&
        portfolios.years.map((year, i) => (
          <button
            className={`portfolio__time--item ${currentYear === year ? 'active' : ''}`}
            onClick={() => changeYear(year)}
            key={i}
          >
            {year !== portfolios.years[portfolios.years.length - 1] ? (
              <span>{year}</span>
            ) : (
              <span>Now</span>
            )}
            <span className="dop">portfolio</span>
          </button>
        ))
        }
      </nav>
      <div className="portfolio__block">
        <div className={`portfolio__list ${tab} ${animation ? 'active' : ''}`} ref={list}>
          {Object.keys(portfolios.group).length > 0 && currentYear &&
          portfolios.group[currentYear].map((item, i) => (
            <div
              className="portfolio__item"
              key={i}
            >
              <div className="portfolio__item--block">
                <h3 className="portfolio__item--title">{item.title}</h3>
                <p className="portfolio__item--text">{item.description}</p>
                <div className="portfolio__item--footer">
                  <Btn className="portfolio__item--btn" link={item.site} text="Site"/>
                  <Btn className="portfolio__item--btn" link={`${routes.portfolio.all}/${item.id}`} text="More" route={true}/>
                </div>
              </div>
              <div className="portfolio__item--image">
                <div className="icons">
                  <div className="square"/>
                  <div className="triangle"/>
                  <div className="circle"/>
                </div>
                <figure className="image">
                  <img src={`/storage/${item.image}`} alt={item.title}/>
                </figure>
              </div>
            </div>
          ))
          }
        </div>
      </div>
    </div>
  )
}

Portfolios.propTypes = {
  portfolios: PropTypes.shape({
    collection: PropTypes.objectOf(PropTypes.shape({
      id: PropTypes.number.isRequired,
      title: PropTypes.string.isRequired,
      site: PropTypes.string,
      image: PropTypes.string.isRequired,
      description: PropTypes.string.isRequired
    })),
    years: PropTypes.array.isRequired,
    group: PropTypes.object.isRequired
  }).isRequired,
  currentYear: PropTypes.number.isRequired,
  tab: PropTypes.string.isRequired,
  animation: PropTypes.bool.isRequired
}

const mapStateToProps = state => ({
  portfolios: state.portfolios.all,
  currentYear: state.portfolios.year,
  tab: state.portfolios.tab,
  animation: state.portfolios.animation
})

export default connect(mapStateToProps)(Portfolios)

// resources/assets/vue/views/portfolio/all.vue
<template>
  <div class="portfolio box-sm">
    <vue-headful :title="header.title" :description="header.description" :head="{
      '[name=robots]' : {content: header.robots}
    }"></vue-headful>
    <nav class="portfolio__time">
      <button v-for="year in portfolios.years"
              :class="['portfolio__time--item', { active: currentYear === year }]" @click="changeYear(year)">
        <span v-if="year !== portfolios.years[portfolios.years.length - 1]">{{year}}</span>
        <span v-else>Now</span>
        <span v-if="$store.getters.getDisplay('mobile')" class="dop">portfolio</span>
      </button>
    </nav>
    <div class="portfolio__block">
      <transition>
        <div v-if="!change" :class="['portfolio__list', $store.state.tab, {active: $store.state.animation}]">
          <div class="portfolio__item" v-for="item in portfolios.group[currentYear]">
            <div class="portfolio__item--block">
              <h3 class="portfolio__item--title">{{item.title}}</h3>
              <p class="portfolio__item--text">{{item.description}}</p>
              <div class="portfolio__item--footer">
                <btn class="portfolio__item--btn" :link="item.site" :text="'Site'"/>
                <btn class="portfolio__item--btn" :link="{name: 'portfolio.one', params: {id: item.id}}" :text="'More'" :route="true"/>
              </div>
            </div>
            <div class="portfolio__item--image">
              <div class="icons">
                <div class="square"></div>
                <div class="triangle"></div>
                <div class="circle"></div>
              </div>
              <figure class="image">
                <img :src="'/storage/'+item.image" :alt="item.title">
              </figure>
            </div>
          </div>
        </div>
      </transition>
    </div>
  </div>
</template>

<script>
  import { mapState } from 'vuex'

  export default {
    data: function () {
      return {
        header: {
          title: 'Koterion | Portfolio',
          description: 'Koterion Portfolio Page',
          robots: 'noindex,nofollow',
          add: 'portfolio'
        },
        change: false
      }
    },
    computed: mapState({
      portfolios: state => state.portfolios.all,
      currentYear: state => state.portfolios.year
    }),
    methods: {
      changeYear(year) {
        if (!this.change) {
          this.change = !this.change

          setTimeout(()=>{
            this.$store.dispatch('portfolios/clickYearTab', year)
            this.change = !this.change
          }, 300)
        }
      }
    }
  }
</script>
