// resources/assets/react/containers/portfolio/one.js
import React, { Component } from 'react'
import Btn from '../../components/btn'

class Portfolio extends Component {
  constructor (props) {
    super(props)
    this.state = {
      header: {},
      portfolio: {
        current: {
          title: "",
          description: "",
          content: "",
          site: "",
          video: "",
          carousel: {
            0: '0',
            1: '1',
            2: '2',
          }
        }
      }
    }
  }
  render () {
    return(
      <div className="portfolio__one box-page">
        <div className="carousel">
          <div className="icons">
            <div className="square"/>
            <div className="triangle"/>
            <div className="circle"/>
          </div>

          <Preview/>
          {this.state.site ? <div className="carousel__after">
            <Btn class="portfolio__one--btn" link={this.state.portfolio.current.site} text="Visit the website"/>
          </div> : ''}
        </div>
        <div className="gui">
          <h1>{ this.state.portfolio.current.title }</h1>
          {this.state.portfolio.current.content}
          <div className="clear"/>
        </div>
        <div className="portfolio__one--footer">

        </div>
      </div>
    )
  }
}

function Preview () {
  let preview

  if(this.state.portfolio.current.video) {
    preview = (
      <video className="portfolio__one--video" src={`/storage/${this.state.portfolio.current.video[0].download_link}`}
             preload="auto" autoPlay loop muted/>)
  } else {
    preview = (
      <div v-else className="glide">
        <div className="glide__track" data-glide-el="track">
          <div className="glide__slides">
            {this.state.portfolio.current.carousel.map((image, i) => {
              return (
                <figure className="glide__slide carousel__image" key={i}>
                  <img src={`/storage/${image}`} alt={`${this.state.portfolio.current.title} slide #${i}`}/>
                </figure>
              )
            })}
          </div>
        </div>
        <div className="glide__bullets" data-glide-el="controls[nav]">
          {this.state.portfolio.current.carousel.map((image, i) => {
            return (<button className="glide__bullet" data-glide-dir={`=${i}`}/>)
          })}
      </div>
      </div>
    )
  }

  return preview
}

export default Portfolio

// resources/assets/vue/views/portfolio/one.vue
<template>
  <div class="portfolio__one box-page">
    <vue-headful :title="portfolio.current.title" :description="portfolio.current.description" :head="{
      '[name=robots]' : {content: header.robots}
    }"></vue-headful>
    <div class="carousel">
      <div class="icons">
        <div class="square"></div>
        <div class="triangle"></div>
        <div class="circle"></div>
      </div>

      <video v-if="portfolio.current.video" class="portfolio__one--video"  :src="portfolio.current.video" preload="auto" autoplay loop muted></video>

      <div v-else class="glide">
        <div class="glide__track" data-glide-el="track">
          <div class="glide__slides">
            <figure v-for="(image, index) in portfolio.images" class="glide__slide carousel__image">
              <img :src="image" :alt="index">
            </figure>
          </div>
        </div>
        <div class="glide__bullets" data-glide-el="controls[nav]">
          <button v-for="(image, index) in portfolio.images" class="glide__bullet" :data-glide-dir="'='+index"></button>
        </div>
      </div>
    </div>
    <div v-if="portfolio.current.site" class="carousel__after">
      <btn :link="portfolio.current.site" :text="'Visit the website'" class="portfolio__one--btn"/>
    </div>
    <div class="gui">
      <h1>{{portfolio.current.title}}</h1>
      <div v-html="portfolio.current.content"></div>
      <div class="clear"></div>
    </div>
    <div class="portfolio__one--footer">
      <btn v-if="portfolio.prev" :link="{name: 'portfolio.one', params: {id: portfolio.prev}}" :text="$store.state.display.current > $store.state.display.padmini ? 'previous project' : 'previous'" :route="true"/>
      <div v-else class="disabled btn">previous <span v-if="$store.state.display.current > $store.state.display.padmini">project</span></div>
      <btn v-if="portfolio.next" :link="{name: 'portfolio.one', params: {id: portfolio.next}}" :text="$store.state.display.current > $store.state.display.padmini ? 'next project' : 'next'" :route="true"/>
      <div v-else class="disabled btn">next <span v-if="$store.state.display.current > $store.state.display.padmini">project</span></div>
    </div>
  </div>
</template>

<script>
  import Glide from '@glidejs/glide'
  import { mapState } from 'vuex'

  let glide = new Glide('.glide', {
    type: 'carousel',
    perView: 1,
    autoplay: 6500
  })

  export default {
    data: function () {
      return {
        header: {
          robots: 'noindex,nofollow'
        }
      }
    },
    watch: {
      '$route.params.id' () {
        this.$store.dispatch('portfolios/fetchPortfolioOne', this.$route.params.id).then(() => {
          if (!this.portfolio.current.video) {
            glide.destroy()
            glide = new Glide('.glide', {
              type: 'carousel',
              perView: 1,
              autoplay: 6500
            }).mount()
          }
        })
      }
    },
    beforeCreate () {
      this.$store.dispatch('portfolios/fetchPortfolioOne', this.$route.params.id).then(() => {
        if (!this.portfolio.current.video) {
          glide.mount()
        }
      })
    },
    computed: mapState({
      portfolio: state => state.portfolios.one
    })
  }
</script>
