// resources/assets/react/containers/portfolio/all.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { getPortfolios, getYear, getPortfolioTab, getPortfolioAnimation } from '../../store/reducers/portfolios'
import { clickYearTab } from '../../store/actions'
import Btn from '../../components/btn'

class Portfolios extends Component {
  constructor (props) {
    super(props)
    this.state = {
      animation: false
    }
  }

  changeYear (year) {
    this.props.dispatch(clickYearTab(year))
  }

  render () {
    let { portfolios, currentYear, tab, animation, routes } = this.props

    return (
      <div className="portfolio box-sm">
        <nav className="portfolio__time">
          {Object.keys(portfolios.years).length > 0 &&
          portfolios.years.map((year, i) => (
            <button
              className={`portfolio__time--item ${currentYear === year ? 'active' : ''}`}
              onClick={() => this.changeYear(year)}
              key={i}
            >
              {year !== portfolios.years[portfolios.years.length - 1] ? (
                <span>{year}</span>
              ) : (
                <span>Now</span>
              )}
              <span className="dop">portfolio</span>
            </button>
          ))
          }
        </nav>
        <div className="portfolio__block">
          <div className={`portfolio__list ${tab} ${animation ? 'active' : ''}`}>
            {Object.keys(portfolios.group).length > 0 && currentYear &&
            portfolios.group[currentYear].map((item, i) => (
              <div
                className="portfolio__item"
                key={i}
              >
                <div className="portfolio__item--block">
                  <h3 className="portfolio__item--title">{item.title}</h3>
                  <p className="portfolio__item--text">{item.description}</p>
                  <div className="portfolio__item--footer">
                    <Btn className="portfolio__item--btn" link={item.site} text="Site"/>
                    <Btn className="portfolio__item--btn" link={`${routes.portfolio.all}/${item.id}`} text="More" route={true}/>
                  </div>
                </div>
                <div className="portfolio__item--image">
                  <div className="icons">
                    <div className="square"/>
                    <div className="triangle"/>
                    <div className="circle"/>
                  </div>
                  <figure className="image">
                    <img src={`/storage/${item.image}`} alt={item.title}/>
                  </figure>
                </div>
              </div>
            ))
            }
          </div>
        </div>
      </div>
    )
  }
}

Portfolios.propTypes = {
  portfolios: PropTypes.shape({
    collection: PropTypes.objectOf(PropTypes.shape({
      id: PropTypes.number.isRequired,
      title: PropTypes.string.isRequired,
      site: PropTypes.string,
      image: PropTypes.string.isRequired,
      description: PropTypes.string.isRequired
    })),
    years: PropTypes.array.isRequired,
    group: PropTypes.object.isRequired
  }).isRequired,
  currentYear: PropTypes.number.isRequired,
  tab: PropTypes.string.isRequired,
  animation: PropTypes.bool.isRequired
}

const mapStateToProps = state => ({
  portfolios: getPortfolios(state.portfolios),
  currentYear: getYear(state.portfolios),
  tab: getPortfolioTab(state.portfolios),
  animation: getPortfolioAnimation(state.portfolios)
})

export default connect(mapStateToProps)(Portfolios)

// resources/views/portfolio/all.vue
<template>
  <div class="portfolio box-sm">
    <nav class="portfolio__time">
      <button v-for="year in portfolio.years"
              :class="['portfolio__time--item', { active: currentYear === year }]" @click="changeYear(year)">
        <span v-if="year !== portfolio.years[portfolio.years.length - 1]">{{year}}</span>
        <span v-else>Now</span>
        <span class="dop">portfolio</span>
      </button>
    </nav>
    <div :class="['portfolio__list',$store.state.tab, {active: $store.state.animation}]">
      <div class="portfolio__item" v-for="item in portfolio.group[currentYear]">
        <div class="portfolio__item--block">
          <h3 class="portfolio__item--title">{{item.title}}</h3>
          <p class="portfolio__item--text">{{item.description}}</p>
          <div class="portfolio__item--footer">
            <btn class="portfolio__item--btn" :link="item.site" :text="'Site'"/>
            <btn class="portfolio__item--btn" :link="{name: 'portfolio.one', params: {id: item.id}}" :text="'More'" :route="true"/>
          </div>
        </div>
        <div class="portfolio__item--image">
          <div class="icons">
            <div class="square"></div>
            <div class="triangle"></div>
            <div class="circle"></div>
          </div>
          <figure class="image">
            <img :src="item.image" :alt="item.title">
          </figure>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import { mapGetters } from 'vuex'
  import Btn from '../components/btn'

  export default {
    data: function () {
      return {
        loading: true,
        header: {
          title: 'Koterion | Portfolio',
          add: 'portfolio'
        }
      }
    },
    components: {
      Btn
    },
    computed: {
      ...mapGetters({
        portfolio: 'getPortfolio',
        currentYear: 'getYear'
      })
    },
    methods: {
      changeYear(year) {
        this.$store.dispatch('clickYearTab', year)
      }
    }
  }
</script>
