// resources/assets/react/components/btn.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import PropTypes from 'prop-types'

function Btn (props) {
  let { route, link, text, className } = props
  return (
    <Link
      to={link}
      className={`btn ${className}`}
      data-text={text}
      target={!route ? '_blank' : ''}
      rel={!route ? 'nofollow' : ''}
    >
      {text}
      <span className="text">{text}</span>
    </Link>
  )
}

Btn.defaultProps = {
  className: '',
  route: false
}

Btn.propTypes = {
  className: PropTypes.string,
  route: PropTypes.bool,
  link: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired
}

export default Btn

// resources/assets/vue/views/components/btn.vue
<template>
  <router-link v-if="route" :to="link" class="btn" :data-text="text">
    {{text}}
    <span v-if="$store.getters.getDisplay('pad')" class="text">{{text}}</span>
  </router-link>
  <a v-else :href="link" class="btn" :data-text="text" target="_blank" rel="nofollow">
    {{text}}
    <span v-if="$store.getters.getDisplay('pad')" class="text">{{text}}</span>
  </a>
</template>

<script>
  export default {
    props: ['text', 'link', 'route'],
    name: 'btn'
  }
</script>
